package com.zhjedu.exam.domain;

import java.util.HashSet;
import java.util.Set;



/**
 * ZjManeuver generated by MyEclipse - Hibernate Tools
 */

public class ZjManeuver  implements java.io.Serializable {


    // Fields    

     private String id;
     private String title;
     private Long createdate;
     private String creator;
     private String maneuverType;
     private Long maneuverPri;
     private String status;
     private Set maneuverItem = new HashSet();

    // Constructors

    /** default constructor */
    public ZjManeuver() {
    }

	/** minimal constructor */
    public ZjManeuver(String title, String status) {
        this.title = title;
        this.status = status;
    }
    
    /** full constructor */
    public ZjManeuver(String title, Long createdate, String creator, String maneuverType, Long maneuverPri, String status) {
        this.title = title;
        this.createdate = createdate;
        this.creator = creator;
        this.maneuverType = maneuverType;
        this.maneuverPri = maneuverPri;
        this.status = status;
    }

   
    // Property accessors

    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }

    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }

    public Long getCreatedate() {
        return this.createdate;
    }
    
    public void setCreatedate(Long createdate) {
        this.createdate = createdate;
    }

    public String getCreator() {
        return this.creator;
    }
    
    public void setCreator(String creator) {
        this.creator = creator;
    }

    public String getManeuverType() {
        return this.maneuverType;
    }
    
    public void setManeuverType(String maneuverType) {
        this.maneuverType = maneuverType;
    }

    public Long getManeuverPri() {
        return this.maneuverPri;
    }
    
    public void setManeuverPri(Long maneuverPri) {
        this.maneuverPri = maneuverPri;
    }

    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

	public Set getManeuverItem() {
		return maneuverItem;
	}

	public void setManeuverItem(Set maneuverItem) {
		this.maneuverItem = maneuverItem;
	}
   








}