package com.zhjedu.exam.domain;

import com.zhjedu.exam.domain.ZjManeuver;



/**
 * ZjManeuverItem generated by MyEclipse - Hibernate Tools
 */

public class ZjManeuverItem  implements java.io.Serializable {


    // Fields    

     private String id;
     private ZjManeuver maneuver;
//     private String parent;
     private String questionType;
     private Long questionNum;
     private String questionScore;


    // Constructors

    /** default constructor */
    public ZjManeuverItem() {
    }

    // Property accessors

    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
//
//    public String getParent() {
//        return this.parent;
//    }
//    
//    public void setParent(String parent) {
//        this.parent = parent;
//    }

    public String getQuestionType() {
        return this.questionType;
    }
    
    public void setQuestionType(String questionType) {
        this.questionType = questionType;
    }

    public Long getQuestionNum() {
        return this.questionNum;
    }
    
    public void setQuestionNum(Long questionNum) {
        this.questionNum = questionNum;
    }

    public String getQuestionScore() {
        return this.questionScore;
    }
    
    public void setQuestionScore(String questionScore) {
        this.questionScore = questionScore;
    }

	public ZjManeuver getManeuver() {
		return maneuver;
	}

	public void setManeuver(ZjManeuver maneuver) {
		this.maneuver = maneuver;
	}
   








}