package com.zhjedu.exam.domain;



/**
 * ZjPaper generated by MyEclipse - Hibernate Tools
 */

public class ZjPaper  implements java.io.Serializable {


    // Fields    

     private String id;
     private String course;
     private String name;
     private String description;
     private String source;
     private String scope;
     private Long totalPoint;
     private Long questionsperpage;
     private String randomquestions;
     private String status;
     private String paperType;
     private String buildType;
     private String location;
     private Long createdate;
     private Long lasteditdate;
     private String creator;
     private String lasteditor;
     private String delflag;


    // Constructors

    /** default constructor */
    public ZjPaper() {
    }

	/** minimal constructor */
    public ZjPaper(String name, Long questionsperpage, String randomquestions, Long createdate, Long lasteditdate, String delflag) {
        this.name = name;
        this.questionsperpage = questionsperpage;
        this.randomquestions = randomquestions;
        this.createdate = createdate;
        this.lasteditdate = lasteditdate;
        this.delflag = delflag;
    }
    
    /** full constructor */
    public ZjPaper(String course, String name, String description, String source, String scope, Long totalPoint, Long questionsperpage, String randomquestions, String status, String paperType, String buildType, String location, Long createdate, Long lasteditdate, String creator, String lasteditor, String delflag) {
        this.course = course;
        this.name = name;
        this.description = description;
        this.source = source;
        this.scope = scope;
        this.totalPoint = totalPoint;
        this.questionsperpage = questionsperpage;
        this.randomquestions = randomquestions;
        this.status = status;
        this.paperType = paperType;
        this.buildType = buildType;
        this.location = location;
        this.createdate = createdate;
        this.lasteditdate = lasteditdate;
        this.creator = creator;
        this.lasteditor = lasteditor;
        this.delflag = delflag;
    }

   
    // Property accessors

    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }

    public String getCourse() {
        return this.course;
    }
    
    public void setCourse(String course) {
        this.course = course;
    }

    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    public String getSource() {
        return this.source;
    }
    
    public void setSource(String source) {
        this.source = source;
    }

    public String getScope() {
        return this.scope;
    }
    
    public void setScope(String scope) {
        this.scope = scope;
    }

    public Long getTotalPoint() {
        return this.totalPoint;
    }
    
    public void setTotalPoint(Long totalPoint) {
        this.totalPoint = totalPoint;
    }

    public Long getQuestionsperpage() {
        return this.questionsperpage;
    }
    
    public void setQuestionsperpage(Long questionsperpage) {
        this.questionsperpage = questionsperpage;
    }

    public String getRandomquestions() {
        return this.randomquestions;
    }
    
    public void setRandomquestions(String randomquestions) {
        this.randomquestions = randomquestions;
    }

    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    public String getPaperType() {
        return this.paperType;
    }
    
    public void setPaperType(String paperType) {
        this.paperType = paperType;
    }

    public String getBuildType() {
        return this.buildType;
    }
    
    public void setBuildType(String buildType) {
        this.buildType = buildType;
    }

    public String getLocation() {
        return this.location;
    }
    
    public void setLocation(String location) {
        this.location = location;
    }

    public Long getCreatedate() {
        return this.createdate;
    }
    
    public void setCreatedate(Long createdate) {
        this.createdate = createdate;
    }

    public Long getLasteditdate() {
        return this.lasteditdate;
    }
    
    public void setLasteditdate(Long lasteditdate) {
        this.lasteditdate = lasteditdate;
    }

    public String getCreator() {
        return this.creator;
    }
    
    public void setCreator(String creator) {
        this.creator = creator;
    }

    public String getLasteditor() {
        return this.lasteditor;
    }
    
    public void setLasteditor(String lasteditor) {
        this.lasteditor = lasteditor;
    }

    public String getDelflag() {
        return this.delflag;
    }
    
    public void setDelflag(String delflag) {
        this.delflag = delflag;
    }
   








}