package com.zhjedu.exam.domain;

/**
 * ZjQuestionOptionListOn generated by MyEclipse Persistence Tools
 */

public class ZjQuestionOptionListOn implements java.io.Serializable {

	// Fields

	private ZjQuestionOptionListOnId id;

	// Constructors

	/** default constructor */
	public ZjQuestionOptionListOn() {
	}

	/** full constructor */
	public ZjQuestionOptionListOn(ZjQuestionOptionListOnId id) {
		this.id = id;
	}

	// Property accessors

	public ZjQuestionOptionListOnId getId() {
		return this.id;
	}

	public void setId(ZjQuestionOptionListOnId id) {
		this.id = id;
	}

}