package com.zhjedu.exam.domain;



/**
 * ZjQuizMidEc generated by MyEclipse - Hibernate Tools
 */

public class ZjQuizMidEc  implements java.io.Serializable {


    // Fields    

     private String id;
     private String quiz;
     private String midExamId;
     private ZjQuiz zjQuiz;

     
    // Constructors

    /** default constructor */
    public ZjQuizMidEc() {
    }

    
    /** full constructor */
    public ZjQuizMidEc(String quiz, String midExamId) {
        this.quiz = quiz;
        this.midExamId = midExamId;
    }
    public ZjQuiz getZjQuiz() {
		return zjQuiz;
	}

	public void setZjQuiz(ZjQuiz zjQuiz) {
		this.zjQuiz = zjQuiz;
	}
   
    // Property accessors

    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }

    public String getQuiz() {
        return this.quiz;
    }
    
    public void setQuiz(String quiz) {
        this.quiz = quiz;
    }

    public String getMidExamId() {
        return this.midExamId;
    }
    
    public void setMidExamId(String midExamId) {
        this.midExamId = midExamId;
    }
   








}