package com.zhjedu.exam.domain;

import com.dfcw.zjproject.zj.model.StudentModel;

/**
 * ZjQuizExam generated by MyEclipse - Hibernate Tools
 */

public class ZjQuizExam implements java.io.Serializable {

	// Fields

	private String id;

	private String quiz;

	private String paper = "";

	private String userid;

	private Long sequence = new Long(0);

	private Long timestart = new Long(0);

	private Long timefinish = new Long(0);

	private Long totalhour = new Long(0);

	private Double grade = new Double(0);

	private String examLocation = "";

	private String status = "0";

	private String postil = "";

	private String reador = "";
	
	private String midExamCourseId = "";

	private ZjQuiz zjQuiz;
	
	private StudentModel student;

	// Constructors

	public ZjQuiz getZjQuiz() {
		return zjQuiz;
	}

	public void setZjQuiz(ZjQuiz zjQuiz) {
		this.zjQuiz = zjQuiz;
	}

	/** default constructor */
	public ZjQuizExam() {
	}

	/** minimal constructor */
	public ZjQuizExam(String quiz, String userid, Long sequence,
			Long timestart, Long timefinish, Double grade, ZjQuiz zjQuiz) {
		this.quiz = quiz;
		this.userid = userid;
		this.sequence = sequence;
		this.timestart = timestart;
		this.timefinish = timefinish;
		this.grade = grade;
		this.zjQuiz = zjQuiz;
	}

	/** full constructor */
	public ZjQuizExam(String quiz, String paper, String userid, Long sequence,
			Long timestart, Long timefinish, Long totalhour, Double grade,
			String examLocation, String status, String postil, String reador, String midExamCourseId, ZjQuiz zjQuiz) {
		this.quiz = quiz;
		this.paper = paper;
		this.userid = userid;
		this.sequence = sequence;
		this.timestart = timestart;
		this.timefinish = timefinish;
		this.totalhour = totalhour;
		this.grade = grade;
		this.examLocation = examLocation;
		this.status = status;
		this.postil = postil;
		this.reador = reador;
		this.midExamCourseId = midExamCourseId;
		this.zjQuiz = zjQuiz;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getQuiz() {
		return this.quiz;
	}

	public void setQuiz(String quiz) {
		this.quiz = quiz;
	}

	public String getPaper() {
		return this.paper;
	}

	public void setPaper(String paper) {
		this.paper = paper;
	}

	public String getUserid() {
		return this.userid;
	}

	public void setUserid(String userid) {
		this.userid = userid;
	}

	public Long getSequence() {
		return this.sequence;
	}

	public void setSequence(Long sequence) {
		this.sequence = sequence;
	}

	public Long getTimestart() {
		return this.timestart;
	}

	public void setTimestart(Long timestart) {
		this.timestart = timestart;
	}

	public Long getTimefinish() {
		return this.timefinish;
	}

	public void setTimefinish(Long timefinish) {
		this.timefinish = timefinish;
	}

	public Long getTotalhour() {
		return this.totalhour;
	}

	public void setTotalhour(Long totalhour) {
		this.totalhour = totalhour;
	}

	public Double getGrade() {
		return this.grade;
	}

	public void setGrade(Double grade) {
		this.grade = grade;
	}

	public String getExamLocation() {
		return this.examLocation;
	}

	public void setExamLocation(String examLocation) {
		this.examLocation = examLocation;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getPostil() {
		return this.postil;
	}

	public void setPostil(String postil) {
		this.postil = postil;
	}

	public String getReador() {
		return this.reador;
	}

	public void setReador(String reador) {
		this.reador = reador;
	}

	public StudentModel getStudent() {
		return student;
	}

	public void setStudent(StudentModel student) {
		this.student = student;
	}

	public String getMidExamCourseId() {
		return midExamCourseId;
	}

	public void setMidExamCourseId(String midExamCourseId) {
		this.midExamCourseId = midExamCourseId;
	}

}