package com.zhjedu.exam.domain;



/**
 * ZjQuizAnswers generated by MyEclipse - Hibernate Tools
 */

public class ZjQuizAnswers  implements java.io.Serializable {


    // Fields    

     private String id;
     private String userid;
     private String exam;
     private String question;
     private String answer;
     private Double grade;


    // Constructors

    /** default constructor */
    public ZjQuizAnswers() {
    }

	/** minimal constructor */
    public ZjQuizAnswers(String userid, String exam, String question, Double grade) {
        this.userid = userid;
        this.exam = exam;
        this.question = question;
        this.grade = grade;
    }
    
    /** full constructor */
    public ZjQuizAnswers(String userid, String exam, String question, String answer, Double grade) {
        this.userid = userid;
        this.exam = exam;
        this.question = question;
        this.answer = answer;
        this.grade = grade;
    }

   
    // Property accessors

    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }

    public String getUserid() {
        return this.userid;
    }
    
    public void setUserid(String userid) {
        this.userid = userid;
    }

    public String getExam() {
        return this.exam;
    }
    
    public void setExam(String exam) {
        this.exam = exam;
    }

    public String getQuestion() {
        return this.question;
    }
    
    public void setQuestion(String question) {
        this.question = question;
    }

    public String getAnswer() {
        return this.answer;
    }
    
    public void setAnswer(String answer) {
        this.answer = answer;
    }

    public Double getGrade() {
        return this.grade;
    }
    
    public void setGrade(Double grade) {
        this.grade = grade;
    }
   








}