package com.zhjedu.exam.domain;



/**
 * ZjManeuverList generated by MyEclipse - Hibernate Tools
 */

public class ZjManeuverList  implements java.io.Serializable {


    // Fields    

     private String id;
     private String quizid;
     private String maneuverCode;
     private String scope;
     private String questionType;
     private Long hard1Num;
     private Long hard2Num;
     private Long hard3Num;
     private Long hard4Num;
     private Long hard5Num;
     private Long nohardNum;
     private String score;
     private String status;


    // Constructors

    /** default constructor */
    public ZjManeuverList() {
    }

	/** minimal constructor */
    public ZjManeuverList(String status) {
        this.status = status;
    }
    
    /** full constructor */
    public ZjManeuverList(String quizid, String maneuverCode, String scope, String questionType, Long hard1Num, Long hard2Num, Long hard3Num, Long hard4Num, Long hard5Num, Long nohardNum, String score, String status) {
        this.quizid = quizid;
        this.maneuverCode = maneuverCode;
        this.scope = scope;
        this.questionType = questionType;
        this.hard1Num = hard1Num;
        this.hard2Num = hard2Num;
        this.hard3Num = hard3Num;
        this.hard4Num = hard4Num;
        this.hard5Num = hard5Num;
        this.nohardNum = nohardNum;
        this.score = score;
        this.status = status;
    }

   
    // Property accessors

    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }

    public String getQuizid() {
        return this.quizid;
    }
    
    public void setQuizid(String quizid) {
        this.quizid = quizid;
    }

    public String getManeuverCode() {
        return this.maneuverCode;
    }
    
    public void setManeuverCode(String maneuverCode) {
        this.maneuverCode = maneuverCode;
    }

    public String getScope() {
        return this.scope;
    }
    
    public void setScope(String scope) {
        this.scope = scope;
    }

    public String getQuestionType() {
        return this.questionType;
    }
    
    public void setQuestionType(String questionType) {
        this.questionType = questionType;
    }

    public Long getHard1Num() {
        return this.hard1Num;
    }
    
    public void setHard1Num(Long hard1Num) {
        this.hard1Num = hard1Num;
    }

    public Long getHard2Num() {
        return this.hard2Num;
    }
    
    public void setHard2Num(Long hard2Num) {
        this.hard2Num = hard2Num;
    }

    public Long getHard3Num() {
        return this.hard3Num;
    }
    
    public void setHard3Num(Long hard3Num) {
        this.hard3Num = hard3Num;
    }

    public Long getHard4Num() {
        return this.hard4Num;
    }
    
    public void setHard4Num(Long hard4Num) {
        this.hard4Num = hard4Num;
    }

    public Long getHard5Num() {
        return this.hard5Num;
    }
    
    public void setHard5Num(Long hard5Num) {
        this.hard5Num = hard5Num;
    }

    public Long getNohardNum() {
        return this.nohardNum;
    }
    
    public void setNohardNum(Long nohardNum) {
        this.nohardNum = nohardNum;
    }

    public String getScore() {
        return this.score;
    }
    
    public void setScore(String score) {
        this.score = score;
    }

    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
   








}