package com.zhjedu.exam.domain;



/**
 * ZjQuestionMatchingOption generated by MyEclipse - Hibernate Tools
 */

public class ZjQuestionMatchingOption  implements java.io.Serializable {


    // Fields    

     private String id;
     private String question;
     private String optioncontent;
     private String answer;


    // Constructors

    /** default constructor */
    public ZjQuestionMatchingOption() {
    }

    
    /** full constructor */
    public ZjQuestionMatchingOption(String question, String optioncontent, String answer) {
        this.question = question;
        this.optioncontent = optioncontent;
        this.answer = answer;
    }

   
    // Property accessors

    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }

    public String getQuestion() {
        return this.question;
    }
    
    public void setQuestion(String question) {
        this.question = question;
    }

    public String getOptioncontent() {
        return this.optioncontent;
    }
    
    public void setOptioncontent(String optioncontent) {
        this.optioncontent = optioncontent;
    }

    public String getAnswer() {
        return this.answer;
    }
    
    public void setAnswer(String answer) {
        this.answer = answer;
    }
   








}