package com.zhjedu.exam.domain;



/**
 * ZjQuestionOption generated by MyEclipse - Hibernate Tools
 */

public class ZjQuestionOption  implements java.io.Serializable {


    // Fields    

     private String id;
     private String question;
     private String optioncontext;
     private String viewflag;


    // Constructors

    /** default constructor */
    public ZjQuestionOption() {
    }

	/** minimal constructor */
    public ZjQuestionOption(String optioncontext) {
        this.optioncontext = optioncontext;
    }
    
    /** full constructor */
    public ZjQuestionOption(String question, String optioncontext, String viewflag) {
        this.question = question;
        this.optioncontext = optioncontext;
        this.viewflag = viewflag;
    }

   
    // Property accessors

    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }

    public String getQuestion() {
        return this.question;
    }
    
    public void setQuestion(String question) {
        this.question = question;
    }

    public String getOptioncontext() {
        return this.optioncontext;
    }
    
    public void setOptioncontext(String optioncontext) {
        this.optioncontext = optioncontext;
    }

    public String getViewflag() {
        return this.viewflag;
    }
    
    public void setViewflag(String viewflag) {
        this.viewflag = viewflag;
    }
   








}