package com.zhjedu.exam.domain;



/**
 * ZjUser generated by MyEclipse - Hibernate Tools
 */

public class ZjUser  implements java.io.Serializable {


    // Fields    

     private String id;
     private String UId;
     private String loginname;
     private String password;
     private String username;
     private String sex;
     private String usertype;


    // Constructors

    /** default constructor */
    public ZjUser() {
    }

	/** minimal constructor */
    public ZjUser(String UId) {
        this.UId = UId;
    }
    
    /** full constructor */
    public ZjUser(String UId, String loginname, String password, String username, String sex, String usertype) {
        this.UId = UId;
        this.loginname = loginname;
        this.password = password;
        this.username = username;
        this.sex = sex;
        this.usertype = usertype;
    }

   
    // Property accessors

    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }

    public String getUId() {
        return this.UId;
    }
    
    public void setUId(String UId) {
        this.UId = UId;
    }

    public String getLoginname() {
        return this.loginname;
    }
    
    public void setLoginname(String loginname) {
        this.loginname = loginname;
    }

    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }

    public String getSex() {
        return this.sex;
    }
    
    public void setSex(String sex) {
        this.sex = sex;
    }

    public String getUsertype() {
        return this.usertype;
    }
    
    public void setUsertype(String usertype) {
        this.usertype = usertype;
    }
   








}