package com.zhjedu.exam.domain;

import org.apache.struts.action.ActionForm;



/**
 * ZjQuestionCategory generated by MyEclipse - Hibernate Tools
 */

public class ZjQuestionCategory extends ActionForm implements java.io.Serializable {


    // Fields    

     private String id;
     private String name;
     private String info;
     private String publishflag = "0";
     private Long createdate = new Long(0);
     private Long lasteditdate = new Long(0);
     private String creator = "";
     private String lasteditor = "";
     private String parent = "";
     private String delflag = "0";
     private String isleaf = "1";

    // Constructors

    /** default constructor */
    public ZjQuestionCategory() {
    }

	/** minimal constructor */
    public ZjQuestionCategory(String name, String publishflag, Long createdate, Long lasteditdate, String creator, String lasteditor, String parent, String delflag) {
        this.name = name;
        this.publishflag = publishflag;
        this.createdate = createdate;
        this.lasteditdate = lasteditdate;
        this.creator = creator;
        this.lasteditor = lasteditor;
        this.parent = parent;
        this.delflag = delflag;
    }
    
    /** full constructor */
    public ZjQuestionCategory(String name, String info, String publishflag, Long createdate, Long lasteditdate, String creator, String lasteditor, String parent, String delflag) {
        this.name = name;
        this.info = info;
        this.publishflag = publishflag;
        this.createdate = createdate;
        this.lasteditdate = lasteditdate;
        this.creator = creator;
        this.lasteditor = lasteditor;
        this.parent = parent;
        this.delflag = delflag;
    }

   
    // Property accessors

    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    public String getInfo() {
        return this.info;
    }
    
    public void setInfo(String info) {
        this.info = info;
    }

    public String getPublishflag() {
        return this.publishflag;
    }
    
    public void setPublishflag(String publishflag) {
        this.publishflag = publishflag;
    }

    public Long getCreatedate() {
        return this.createdate;
    }
    
    public void setCreatedate(Long createdate) {
        this.createdate = createdate;
    }

    public Long getLasteditdate() {
        return this.lasteditdate;
    }
    
    public void setLasteditdate(Long lasteditdate) {
        this.lasteditdate = lasteditdate;
    }

    public String getCreator() {
        return this.creator;
    }
    
    public void setCreator(String creator) {
        this.creator = creator;
    }

    public String getLasteditor() {
        return this.lasteditor;
    }
    
    public void setLasteditor(String lasteditor) {
        this.lasteditor = lasteditor;
    }

    public String getParent() {
        return this.parent;
    }
    
    public void setParent(String parent) {
        this.parent = parent;
    }

    public String getDelflag() {
        return this.delflag;
    }
    
    public void setDelflag(String delflag) {
        this.delflag = delflag;
    }

	public String getIsleaf() {
		return isleaf;
	}

	public void setIsleaf(String isleaf) {
		this.isleaf = isleaf;
	}
   








}